[package]
org = "car_rental_system"
name = "car_rental_system"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[[package.modules]]
name = "car_rental_system.customer.admin"
org = "car_rental_system"
version = "0.1.0"